import { FC } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Footer from './_components/Footer/Footer';

import './globals.css';
import Nav from './_components/Nav/Nav';
import StoreProvider from './_components/StoreProvider/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout: FC<
	Readonly<{
		children: React.ReactNode;
	}>
> = ({ children }) => {
	return (
		<html lang='en'>
			<StoreProvider>
				<body className={inter.className}>
					<Nav />
					<div className='Container'>{children}</div>
					<Footer />
				</body>
			</StoreProvider>
		</html>
	);
};

export default RootLayout;
